name: quantify
description: A type-safe unit of measurement converter library for Dart with elegant syntax, high precision, and optimal performance.
version: 0.13.0

homepage: https://github.com/PhilippHGerber/quantify
repository: https://github.com/PhilippHGerber/quantify
issue_tracker: https://github.com/PhilippHGerber/quantify/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ">=0.18.1 <0.21.0"
  meta: ^1.16.0

dev_dependencies:
  test: ^1.26.0
  very_good_analysis: ^10.0.0

topics:
  - units
  - unit-converter
  - measurement
  - conversion
  - physics

screenshots:
  - description: "Quantify - Convert SI Units"
    path: pub/quantify.webp
